// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt08mb5A1op1MZAbg7fc9f5dCDdUPkmd0',
    appId: '1:453541164446:web:66077dd788501ecdf7528f',
    messagingSenderId: '453541164446',
    projectId: 'test-c4d9f',
    authDomain: 'test-c4d9f.firebaseapp.com',
    storageBucket: 'test-c4d9f.firebasestorage.app',
    measurementId: 'G-EMG4W4EP4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMjQaSSnJhxhdsnvVZlk2L_uX4Hlq_8kw',
    appId: '1:453541164446:android:da1b250051af3b06f7528f',
    messagingSenderId: '453541164446',
    projectId: 'test-c4d9f',
    storageBucket: 'test-c4d9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZj1gy3dwbs8wKAjOkzJ6RofeWNJt50Vs',
    appId: '1:453541164446:ios:315e93528ad4568ff7528f',
    messagingSenderId: '453541164446',
    projectId: 'test-c4d9f',
    storageBucket: 'test-c4d9f.firebasestorage.app',
    iosBundleId: 'com.example.cinemaLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZj1gy3dwbs8wKAjOkzJ6RofeWNJt50Vs',
    appId: '1:453541164446:ios:315e93528ad4568ff7528f',
    messagingSenderId: '453541164446',
    projectId: 'test-c4d9f',
    storageBucket: 'test-c4d9f.firebasestorage.app',
    iosBundleId: 'com.example.cinemaLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt08mb5A1op1MZAbg7fc9f5dCDdUPkmd0',
    appId: '1:453541164446:web:bd2814b4abfc3726f7528f',
    messagingSenderId: '453541164446',
    projectId: 'test-c4d9f',
    authDomain: 'test-c4d9f.firebaseapp.com',
    storageBucket: 'test-c4d9f.firebasestorage.app',
    measurementId: 'G-NCS5MQ7B3L',
  );
}
